import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'benjaminran' at '4/3/16 7:27 PM' with Gradle 2.11
 *
 * @author benjaminran, @date 4/3/16 7:27 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
