build/streams.jar:
	- mkdir build
	- rm build/streams.jar
	javac -d build src/main/java/com/benjaminran/practice/streams/Streams.java && jar -cmf src/main/resources/manifest.txt build/streams.jar -C build com
